-- Seed: real "The Old Place" menu, generated from src/utils/mockData.js.
-- Idempotent: clears the three content tables first, then re-inserts.

truncate table public."menuItems" restart identity cascade;
truncate table public.categories restart identity cascade;
delete from public."cafeDetails";

insert into public.categories (id, name, icon) values
  (1, 'Coffee', 'Coffee'),
  (2, 'Tea', 'Leaf'),
  (3, 'Hot Chocolate', 'Milk'),
  (4, 'Soft drinks', 'CupSoda'),
  (5, 'Freshly made', 'Citrus'),
  (6, 'Beer', 'Beer'),
  (7, 'Wine', 'Wine'),
  (8, 'Spirits', 'Martini'),
  (9, 'Shots', 'FlaskConical'),
  (10, 'Long drinks', 'GlassWater'),
  (11, 'Snacks', 'Cookie');
select setval(pg_get_serial_sequence('public.categories','id'), (select max(id) from public.categories));

insert into public."menuItems" (name, category_id, price, description, subcategory) values
  ('Espresso', 1, '5.5', '20ml', null),
  ('Espresso dublu cu lapte', 1, '11.5', 'Double espresso with milk', null),
  ('Ristretto', 1, '5.5', '20ml, concentrated espresso', null),
  ('Espresso dublu', 1, '11', '40ml', null),
  ('Americano', 1, '6', 'Espresso, hot water', null),
  ('Cappucino', 1, '7', 'Espresso, steamed milk, milk foam', null),
  ('Cappucino vienez', 1, '7', 'Espresso, whipped cream', null),
  ('Cafe Latte', 1, '8', 'Espresso, steamed milk', null),
  ('Ice Coffee', 1, '8', 'Cold espresso, milk, ice', null),
  ('Moccacino', 1, '9', 'Espresso, chocolate, steamed milk', null),
  ('Frappe', 1, '9', 'Iced blended coffee', null),
  ('Irish Coffee', 1, '11', 'Espresso, Irish whiskey, whipped cream', null),
  ('+ Arome extra', 1, '1', 'Pumpkin spice, vanilie, cookie chocolate', null),
  ('Ceai verde', 2, '8', 'Le touareg · Passion fruit', null),
  ('Ceai fructe', 2, '8', 'Wild berry · Rum cream', null),
  ('Ceai rosu', 2, '8', 'Fire side', null),
  ('Ceai negru', 2, '8', 'Copa cabana', null),
  ('Ciocolata neagra', 3, '8', 'Dark chocolate · + topping optional', null),
  ('Ciocolata alba', 3, '8', 'White chocolate · + topping optional', null),
  ('Pepsi', 4, '8', '330ml / 500ml · diverse sortimente', null),
  ('Mirinda', 4, '8', '330ml / 500ml · diverse sortimente', null),
  ('Lipton', 4, '8', '330ml / 500ml · diverse sortimente', null),
  ('Prigat', 4, '8', '330ml / 500ml · diverse sortimente', null),
  ('7up', 4, '8', '330ml / 500ml', null),
  ('MountainDew', 4, '8', '330ml / 500ml', null),
  ('Apa plata / carbogazoasa', 4, '6', null, null),
  ('Evervess tonic', 4, '7', '250ml', null),
  ('Mellow', 4, '13', 'Apple, orange, mango', null),
  ('Fritz kola', 4, '13', null, null),
  ('Red Bull', 4, '10', '250ml', null),
  ('Rockstar', 4, '10', '250ml', null),
  ('Limonada', 5, '10', 'Lamaie, portocale, papaya, fructe de padure, fruct de cactus, pepne galben · 400ml', null),
  ('Milkshake', 5, '10', 'Ciocolata, vanilie · 300ml', null),
  ('Smoothie', 5, '10', 'Papaya, fructe de padure, fruct de cactus, pepne galben · 300ml', null),
  ('Staropramen', 6, '7', 'Sticla / halba · 500ml / 400ml · 5% alc.', null),
  ('Becks', 6, '7.5', '500ml / 300ml · 5% alc.', null),
  ('Stella Artois', 6, '10', '330ml · 4.40% alc.', null),
  ('Corona', 6, '13', '330ml · 4.5% alc.', null),
  ('Sommersby', 6, '10', 'Mure, afine, mere · 330ml · 4.5% alc.', null),
  ('Bergenbier 0%', 6, '8', 'Fara alcool', null),
  ('Bergenbier fresh', 6, '8', null, null),
  ('Fresh', 6, '8', null, null),
  ('Bravoure Alb Sec', 7, '75', '13% alc. · 750ml', 'Crama Chateau Cristi'),
  ('Bravoure Rosu Sec', 7, '75', '13.5% alc. · 750ml', 'Crama Chateau Cristi'),
  ('Metamorfosis Alb Sec', 7, '50', '13% alc. · 750ml', 'Crama Dealu'' Mare'),
  ('Metamorfosis Rosu Sec', 7, '50', '14.5% alc. · 750ml', 'Crama Dealu'' Mare'),
  ('Nomad Alb Sec', 7, '60', '13% alc. · 750ml', 'Crama Aurelia Visinescu'),
  ('Nomad Rosu Sec', 7, '60', '14.5% alc. · 750ml', 'Crama Aurelia Visinescu'),
  ('Frittman Irsai Oliver', 7, '50', '12% alc. · 750ml', 'Crama Kunsag'),
  ('Frittman Cserszegi Fuszeres', 7, '50', '12.5% alc. · 750ml', 'Crama Kunsag'),
  ('Mosia Alb Demisec', 7, '40', '12% alc. · 750ml', 'Crama Tohani'),
  ('Mosia Rosu Demisec', 7, '40', '13.5% alc. · 750ml', 'Crama Tohani'),
  ('Mosia Rose Demisec', 7, '40', '13% alc. · 750ml', 'Crama Tohani'),
  ('Alb sec', 7, '15', '12.9% alc. · 500ml', 'Vin la Carafa'),
  ('Rosu demidulce', 7, '15', '10.5% alc. · 500ml', 'Vin la Carafa'),
  ('Rose demidulce', 7, '15', '10.5% alc. · 500ml', 'Vin la Carafa'),
  ('Husi Alb Demidulce', 7, '40', '13% alc. · 750ml', 'Crama Averesti'),
  ('Husi Rosu Demidulce', 7, '40', '13.5% alc. · 750ml', 'Crama Averesti'),
  ('Sprit mic', 7, '4', '100ml vin + 200ml apa', 'Sprit'),
  ('Sprit mare', 7, '7', '200ml vin + 200ml apa', 'Sprit'),
  ('Jack Daniels', 8, '5 / 12.5', '20ml / 50ml', 'Whiskey'),
  ('Gentleman Jack', 8, '6 / 15', '20ml / 50ml', 'Whiskey'),
  ('Chivas Regal', 8, '6 / 15', '20ml / 50ml', 'Whiskey'),
  ('Tullamore', 8, '5 / 12.5', '20ml / 50ml', 'Whiskey'),
  ('Jim Beam', 8, '4 / 10', '20ml / 50ml', 'Whiskey'),
  ('J & B', 8, '4 / 10', '20ml / 50ml', 'Whiskey'),
  ('Jameson', 8, '5 / 12.5', '20ml / 50ml', 'Whiskey'),
  ('Fireball', 8, '5 / 12.5', '20ml / 50ml', 'Whiskey'),
  ('Absolut', 8, '4 / 10', '20ml / 50ml', 'Vodka'),
  ('Finalndia', 8, '4 / 10', '20ml / 50ml', 'Vodka'),
  ('Danzka', 8, '4 / 10', '20ml / 50ml', 'Vodka'),
  ('Stalinskaya', 8, '3 / 7.5', '20ml / 50ml', 'Vodka'),
  ('Alexander lemon', 8, '3 / 7.5', '20ml / 50ml', 'Vodka'),
  ('Jidvei', 8, '10', '50ml', 'Cognac'),
  ('Metaxa 5*', 8, '10', '50ml', 'Cognac'),
  ('Metaxa 7*', 8, '12.5', '50ml', 'Cognac'),
  ('Alexandrion 5*', 8, '7.5', '50ml', 'Cognac'),
  ('Courvoisier', 8, '15', '50ml', 'Cognac'),
  ('Stroh 60', 8, '5 / 12.5', '20ml / 50ml', 'Rom'),
  ('Stroh Jagertee', 8, '5 / 12.5', '20ml / 50ml', 'Rom'),
  ('Captain Morgan gold spice', 8, '5 / 12.5', '20ml / 50ml', 'Rom'),
  ('Captain Morgan black', 8, '5 / 12.5', '20ml / 50ml', 'Rom'),
  ('Captain Morgan white', 8, '5 / 12.5', '20ml / 50ml', 'Rom'),
  ('Unicum', 8, '12.5', '50ml', 'Digestive'),
  ('Unicum szilva', 8, '12.5', '50ml', 'Digestive'),
  ('Martini Bianco / Rosso', 8, '9', '50ml', 'Digestive'),
  ('Jagermeister', 8, '12.5', '50ml', 'Digestive'),
  ('Jager', 9, '5', '20ml', null),
  ('Unicum', 9, '5', '20ml', null),
  ('Tequila', 9, '5', '20ml', null),
  ('Tatratea', 9, '6', '20ml', null),
  ('Absinth', 9, '5', '20ml', null),
  ('Becherovka', 9, '5', '20ml', null),
  ('Fireball', 9, '5', '20ml', null),
  ('Gin tonic', 10, '18', null, null),
  ('Cuba libre', 10, '18', null, null),
  ('Jager Bomb', 10, '18', '2 buc. · 185ml', null),
  ('Vodka orange', 10, '18', null, null),
  ('Vodka tonic', 10, '18', null, null),
  ('Pringles', 11, '17', null, null),
  ('Alune', 11, '7', null, null),
  ('Saratele', 11, '7', null, null);

insert into public."cafeDetails" (id, name, "logoUrl", address, phone, slogan, hours) values
  (1, 'The Old Place', '', 'Strada Petru Bran 17, 440027 Satu Mare', '0744 664 997', 'Cafe & Pub', '[{"day":"Mon – Fri","time":"7:30 am – 12 am"},{"day":"Saturday","time":"10 am – 1 am"},{"day":"Sunday","time":"10 am – 12 am"}]'::jsonb);
select setval(pg_get_serial_sequence('public."cafeDetails"','id'), 1);
