-- Digital menu schema for "The Old Place".
--
-- Table and column names use the exact casing the frontend already queries
-- (e.g. supabase.from('menuItems'), cafeDetails.logoUrl), so camelCase
-- identifiers are quoted to preserve case.
--
-- SECURITY MODEL (option 2 / server-side secret):
--   * The public/anon role can only READ the menu tables.
--   * All writes go through the /api/admin serverless function, which uses the
--     service_role key (which bypasses RLS) after verifying an admin token.
--   * The `settings` table is locked to public roles entirely.
--   * The `images` bucket is public-read; uploads use signed URLs minted by the
--     function, so anon has no storage write access.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.categories (
  id   bigint generated by default as identity primary key,
  name text   not null,
  icon text   not null default 'Utensils'
);

create table if not exists public."cafeDetails" (
  id        bigint generated by default as identity primary key,
  name      text,
  "logoUrl" text,
  address   text,
  phone     text,
  slogan    text,
  hours     jsonb not null default '[]'::jsonb
);

create table if not exists public."menuItems" (
  id          bigint generated by default as identity primary key,
  name        text   not null,
  category_id bigint references public.categories (id) on delete cascade,
  price       text   not null,
  description text,
  subcategory text,
  image       text
);

create index if not exists "menuItems_category_id_idx"
  on public."menuItems" (category_id);

-- Single-row table (id = 1) holding the admin password hash. The Login screen
-- does UPDATE ... WHERE id = 1, so the row must exist up front or the update
-- silently affects 0 rows.
create table if not exists public.settings (
  id                  bigint primary key,
  admin_password_hash text
);

insert into public.settings (id, admin_password_hash)
values (1, null)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Data API exposure (tables are no longer auto-exposed as of 2026-04-28)
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

-- Public roles can only READ the three menu tables. Writes happen via the
-- service_role inside /api/admin. The `settings` table gets no public grant.
grant select
  on public.categories, public."cafeDetails", public."menuItems"
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.categories    enable row level security;
alter table public."cafeDetails" enable row level security;
alter table public."menuItems"   enable row level security;
alter table public.settings      enable row level security;

-- Public read-only on menu tables (service_role bypasses RLS for writes).
create policy "public read" on public.categories
  for select to anon, authenticated using (true);

create policy "public read" on public."cafeDetails"
  for select to anon, authenticated using (true);

create policy "public read" on public."menuItems"
  for select to anon, authenticated using (true);

-- settings: RLS enabled with no public policy/grant => no anon access at all.

-- ---------------------------------------------------------------------------
-- Storage: public "images" bucket for logos and menu item photos
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- Public bucket => anyone can read. Writes use signed upload URLs minted by the
-- service_role in /api/admin, so no anon write policy is needed.
create policy "images read" on storage.objects
  for select to anon, authenticated using (bucket_id = 'images');
